### ISSUE TITLE
Coil returned an image that is missing from its disk cache

### ISSUE THREAD

**Issue by latsson** [saket/telephoto#106]
Hey!

Thanks for a really nice library. This is the only one I found in Compose that keeps the quality of the image while zooming.

When rolling this out in a large app we have noticed a bunch of crashes. This seems to happen for all devices on all OS versions. No idea how to reproduce it though.

```
Fatal Exception: java.lang.IllegalStateException: Coil returned an image that is missing from its disk cache
       at me.saket.telephoto.zoomable.coil.Resolver.toSubSamplingImageSource(CoilImageSource.kt:187)
       at me.saket.telephoto.zoomable.coil.Resolver.access$toSubSamplingImageSource(CoilImageSource.kt)
       at me.saket.telephoto.zoomable.coil.Resolver$toSubSamplingImageSource$1.invokeSuspend(CoilImageSource.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
        
My code (inside a HorizontalPager)

```
val zoomState = rememberZoomableImageState(
    zoomableState = rememberZoomableState(
        zoomSpec = ZoomSpec(maxZoomFactor = 3f),
    ),
)

ZoomableAsyncImage(
    model = mediaItem.url,
    contentDescription = mediaItem.altText,
    state = zoomState,
)
```

Version used:
`telephotoZoomableImageCoil = { module = "me.saket.telephoto:zoomable-image-coil", version = "0.13.0" }
`

**Comment by saket** [comment]
Hmm it's weird that coil is returning a null entry from its disk cache despite reporting a non-null disk cache key. https://github.com/saket/telephoto/blob/dd794df0fb8a007d8e92abab9707bb54071e592b/zoomable-image/coil/src/main/kotlin/me/saket/telephoto/zoomable/coil/CoilImageSource.kt#L181-L189

@latsson Are there any other useful breadcrumbs left by your error reporting service?

**Comment by saket** [comment]
@colinrtwhite are there any other edge cases related to disk caching that I might be missing?

This is probably another example of why I wish Coil had a public API for downloading images to disk.

**Comment by latsson** [comment]
> Hmm it's weird that coil is returning a null entry from its disk cache despite reporting a non-null disk cache key.
> 
> https://github.com/saket/telephoto/blob/dd794df0fb8a007d8e92abab9707bb54071e592b/zoomable-image/coil/src/main/kotlin/me/saket/telephoto/zoomable/coil/CoilImageSource.kt#L181-L189
> 
> @latsson Are there any other useful breadcrumbs left by your error reporting service?

Sadly nothing other of interest 😐 It's just twice as common as the other 2 I wrote about.

**Comment by colinrtwhite** [comment]
@saket I think there's a couple potential cases where `result.diskCacheKey` could be non-null by the time `openSnapshot` is called:

- Another request starts writing to the same cache entry after the image data was written, but before `openSnapshot` is called. Coil's `DiskCache` doesn't allow simultaneous reads + writes as it's not possible since it exposes the underlying file path.
- Android's cache directory gets cleared after the image data was written, but before `openSnapshot` is called. The system can do this at any time, though I believe it won't delete files with an open `source`/`sink` (not 100% on this).

I think what Telefoto is looking for is an atomic API that writes the image data to disk then immediately opens a `source` for the file. That way we avoid the race condition between writing the image data and calling `openSnapshot`.

Could you open a [feature request](https://github.com/coil-kt/coil/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=) on Coil's tracker so we can track? 🙏🏻

**Comment by saket** [comment]
Done, thank you! https://github.com/coil-kt/coil/issues/2630

**Comment by spencergriffin** [comment]
Any update on this, or new ideas on how to address it? We recently added telephoto to our app, and I haven't been able to reproduce the crash but we are seeing it a lot in our logs.

**Comment by saket** [comment]
Nothing yet. I'm thinking of handling this by suppressing the error and displaying a smaller, non sub-sampled image instead. Your users won't see full resolution copies of their images, but I suppose this is a good enough compromise?

**Comment by shanestaples** [comment]
Hey @saket ! Thanks again for providing this great library! 

We've just switched our implementation back to `ZoomableAsyncImage` from the `.zoomable` modifier, and we are also seeing this new crash in our Sentry logs. It's fairly low occurring, however it is an unhanded exception resulting in app crash.

Is there any update on the possible progress for this one? For our use case, we would also be totally fine with your proposed solution above to show users a smaller, non sub-sampled image instead of crashing. 🙏

**Comment by saket** [comment]
Yeah, I guess I've waited long enough to come up with a better idea. Let me fallback to a non-sub-sampled image to suppress these crashes for y'all!

**Comment by ablenesi** [comment]
Any plans to create a release with this fix?

**Comment by saket** [comment]
I'll try to cut a release today

**Comment by saket** [comment]
Released with https://github.com/saket/telephoto/releases/tag/0.19.0. This will hopefully bring down the crashes for y'all. Let me know how it goes!
