### ISSUE TITLE
Issue with loading the AVIF image

### ISSUE THREAD

**Issue by mrmike** [saket/telephoto#118]
## Context
I've encountered an issue loading the AVIF image using the telephoto library. Interestingly, the same image loads correctly when using `AsyncImage` from the coil. 

After comparing events generated by `EventListener` from coil and telephoto I've noticed that telephoto only reaches `resolveSizeStart` event. I suspect that the issue is related to resolving the image size. Further debugging revealed that `canvasSize` is never emitted b/c `filter` condition is always `false` but I have no clue why this is happening 🤔 
```
  val resolved = key(image) {
    image.resolve(
      canvasSize = remember {
        snapshotFlow { canvasSize }.filter { it.isSpecified && !it.isEmpty() }
      }
    )
  }
```

* Coil version `3.0.4`
* Telephoto version `0.14.0`
* Android SDK 35

## Example 
```
@Composable
fun AvifImageLoader() {
    val image = "https://raw.githubusercontent.com/link-u/avif-sample-images/refs/heads/master/fox.profile0.8bpc.yuv420.avif"

    // Using AsyncImage from Coil works fine
    ZoomableAsyncImage(
        model = image,
        contentDescription = null,
    )
}
```

**Comment by mrmike** [comment]
Ok, I think the issue is caused by the fact that `BitmapRegionDecoder` is not supporting AVIF format 
```
java.io.IOException: Image format not supported
at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:102).   
at me.saket.telephoto.subsamplingimage.FileImageSource.decoder(SubSamplingImageSource.kt:167)
at me.saket.telephoto.subsamplingimage.internal.AndroidImageRegionDecoder$Companion$Factory$1$1.invokeSuspend(AndroidImageRegionDecoder.kt:100)
```

**Comment by saket** [comment]
We could disable sub-sampling if `BitmapRegionDecoder` throws an error. Wanna help me out? I'd start by adding an error reporter here:

https://github.com/saket/telephoto/blob/29f9b5afcf2a021cc2d5e68767beb896b7cdd532/zoomable-image/core/src/main/kotlin/me/saket/telephoto/zoomable/ZoomableImage.kt#L207-L211

When a callback to `onImageLoadingFailed()` is received, `ZoomableImage` could override its [resolved](https://github.com/saket/telephoto/blob/29f9b5afcf2a021cc2d5e68767beb896b7cdd532/zoomable-image/core/src/main/kotlin/me/saket/telephoto/zoomable/ZoomableImage.kt#L83) value by a fall-back `ZoomableImageSource.PainterDelegate`.

**Comment by mrmike** [comment]
Providing empty `SubSamplingImageErrorReporter` was enough to make image to load. My assuption is that `RealSubSamplingImageState` is able to provide state when decoder is not present (just `LoadImageTilesEffect` is not going to work). 

I was getting crash because I was testing on debug build where `NoOpInRelease` reporter rethrows exception for `BuildConfig.DEBUG`. 

Do you think it is still beneficial to provide falback for `ZoomableImageSource.PainterDelegate` in that scenario?

**Comment by saket** [comment]
Lol that is a funny side-effect of the fact that `SubSamplingImage()` displays a placeholder image generated by Coil. I guess we could change the default error reporter to not crash for situations like this.

**Comment by saket** [comment]
The next version of telephoto will disable sub-sampling of AVIF images by default: https://github.com/saket/telephoto/commit/9d2e2b218f5ee6e1a71e1fa237eb473e20f6c301. Thanks for reporting this!

I also filed a feature request for Android to support sampling of AVIF images: https://issuetracker.google.com/u/0/issues/392661391.

**Comment by mrmike** [comment]
Thank you @saket!

**Comment by saket** [comment]
@mrmike would you be able to try this out using `0.15.0-SNAPSHOT`?

**Comment by mrmike** [comment]
@saket I checked the `0.15.0-SNAPSHOT` and I can confirm that reported issue is fixed 🎉  Thanks!

**Comment by saket** [comment]
Thanks for confirming! This is now available as part of 0.15.0: https://github.com/saket/telephoto/releases/tag/0.15.0

**Comment by saket** [comment]
AVIF support has been added to `BitmapRegionDecoder`: https://issuetracker.google.com/issues/392661391#comment3. I'll try giving it a go.
