### ISSUE TITLE
Crash when clearing the cache while app is in the background

### ISSUE THREAD

**Issue by MV-GH** [saket/telephoto#37]
When having my app in the background and then clearing the cache through appinfo in android settings. Upon entering the app and selecting a image (which creates a ZoomableAsyncImage), it crashes. Other than that your library has been working great!

Version: 1.0.0-alpha02

<details> <summary>stacktrace </summary>
FATAL EXCEPTION: main
Process: com.jerboa, PID: 8240
java.lang.IllegalStateException: Coil returned a null image from disk cache
	at me.saket.telephoto.zoomable.coil.Resolver.work(Unknown Source:245)
	at me.saket.telephoto.zoomable.coil.Resolver$work$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Unknown Source:6)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(Unknown Source:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:31)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.EventLoopImplPlatform.processUnconfinedEvent(Unknown Source:23)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(Unknown Source:116)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(Unknown Source:2)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(Unknown Source:6)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(Unknown Source:94)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(Unknown Source:51)
	at kotlinx.coroutines.channels.BufferedChannel.trySend-JP2dKIU(Unknown Source:107)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1.invoke(SourceFile:12)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1.invoke(SourceFile:2)
	at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Unknown Source:73)
	at androidx.compose.material.Strings$Companion.sendApplyNotifications(Unknown Source:29)
	at androidx.compose.ui.platform.GlobalSnapshotManager$ensureStarted$1.invokeSuspend(Unknown Source:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(Unknown Source:22)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@921ce6a, Dispatchers.Main.immediate]

</details>

**Comment by saket** [comment]
Hmm if coil says it still has images in its disk cache even after the cache is cleared then I'm afraid I can't do anything here. Wanna recreate this issue on https://github.com/coil-kt/coil/issues instead?

**Comment by MV-GH** [comment]
I'll see if I can reproduce this with AsyncImage and then I'll make an issue on coil repo.

**Comment by saket** [comment]
I think this is slightly difficult to reproduce with `AsyncImage` because it will skip its disk cache when images are cached in memory. Telephoto, on the other hand, can't read from memory. It assumes that images are always available on disk because it sets coil's `diskCachePolicy` to `CachePolicy.ENABLED`. 

@colinrtwhite would you have any ideas on how I can handle this? Coil does not re-write images to the disk cache when they're read from the memory. Could Coil detect if its disk cache was deleted and maybe bust its memory cache?

**Comment by colinrtwhite** [comment]
@saket Hmm this is a tough one. I don't think we want to clear an item from the memory cache if it's been removed from the disk cache because:

- This reduces the memory cache hit rate, which we want to maximize.
- This would require us to perform a disk cache read on the main thread for every memory cache hit, which would be slow.

My first instinct to handle this would be to:

- Perform a request as usual.
- If `diskCache.openSnapshot(diskCacheKey)` is null, handle it gracefully by retrying the request with `memoryCachePolicy(CachePolicy.DISABLED)` to skip the memory cache.
- If `diskCache.openSnapshot(diskCacheKey)` is still null then log an error.

Overall, I'd avoid using `!!` with `diskCache.openSnapshot(diskCacheKey)` as there are other cases where it's not possible to open a snapshot for an entry (cache corruption, someone else already opened an `Editor` for that key, etc.).

**Comment by Hospes** [comment]
Hey guys, I have this kind of crash in crash reporting also. It's not very often but anyway it happens. I would like to have some fix for that. 💯

**Comment by saket** [comment]
Took me a while, but this should be fixed by [v0.11.2](https://github.com/saket/telephoto/releases/tag/0.11.2). `ZoomableAsyncImage()` will now reload images if the disk cache is found empty before throwing an error, as suggested by @colinrtwhite.
