### ISSUE TITLE
Swapping between multiple images

### ISSUE THREAD

**Issue by pikzen** [saket/telephoto#40]
Hi! I've been trying to use telephoto with a slightly specific need: I have multiple images that get swapped between different zoom levels (basically, more zoomed: more detail available on the image). Previous code used TileView (https://github.com/moagrius/TileView) which required the image to be split in many, many tiles. My current attempt swaps just the model depending on ZoomableState.zoomFraction. However, telephoto's code emits events as the zoom goes on, and ends up calling .location on an Unspecified state. Which is not surprising, it'll be the first time that image gets loaded, so no re-init can be done, so it crashes directly.

(Along with other undesired behaviors that happen with double taps, etc, but then again, that's probably not an expected use case anyways)

```
java.lang.UnsupportedOperationException
at me.saket.telephoto.zoomable.ZoomableContentLocation$Unspecified.location-TmRCtEA(ZoomableContentLocation.kt:75)
at me.saket.telephoto.zoomable.ZoomableContentLocation$Unspecified.location-TmRCtEA(ZoomableContentLocation.kt:73)
at me.saket.telephoto.zoomable.ZoomableState$unscaledContentBounds$2.invoke(ZoomableState.kt:184)
at me.saket.telephoto.zoomable.ZoomableState$unscaledContentBounds$2.invoke(ZoomableState.kt:183)
at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:161)
at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:224)
at me.saket.telephoto.zoomable.ZoomableState.getUnscaledContentBounds(ZoomableState.kt:582)
at me.saket.telephoto.zoomable.ZoomableState.access$getUnscaledContentBounds(ZoomableState.kt:88)
at me.saket.telephoto.zoomable.ZoomableState$transformableState$1.invoke-0DeBYlg(ZoomableState.kt:201)
at me.saket.telephoto.zoomable.ZoomableState$transformableState$1.invoke(ZoomableState.kt:197)
at me.saket.telephoto.zoomable.internal.DefaultTransformableState$transformScope$1.transformBy-0DeBYlg(transformableState.kt:111)
at me.saket.telephoto.zoomable.internal.TransformableKt$transformable$3$1$1.invokeSuspend(transformable.kt:103)
...
```

Is this something you've already considered / do not plan on supporting ? I could probably have one ZoomableAsyncImage per layer, and attempt to transfer various state info as we transition from layer to layer, but I just wanted to check in here before. Absolutely understand if this usecase is not something you plan on supporting.

**Comment by saket** [comment]
It sounds like you want to use `SubSamplingImage()` directly which will handle tiling for you, but it is currently coupled with android's `BitmapRegionDecoder`. Will you be able to implement your usecase if `SubSamplingImage()` allowed you to pass in your own image provider for the tiles?

**Comment by pikzen** [comment]
In my use case, each layer has a different sized image that acts as different levels of detail (1024x1024 overview, 2048x2048, 4096x4096, 8192x8192 high detail), which would mean also adapting the coordinates to stay centered on the same tile, etc. I'd need to explore a bit what such an API would entail (I would assume that it would be said provider's responsibility to call decodeRegion on the appropriate parts), but theoretically it should work.

**Comment by saket** [comment]
> In my use case, each layer has a different sized image that acts as different levels of detail (1024x1024 overview, 2048x2048, 4096x4096, 8192x8192 high detail), which would mean also adapting the coordinates to stay centered on the same tile, etc.

Yep this is exactly how `SubSamplingImage` displays huge images!

I'd suggest cloning telephoto and trying out if the proposed changes will work for you.

**Comment by saket** [comment]
@pikzen I'm going ahead and marking this issue as closed. Please reopen if you still need help with `SubSamplingImage`?

**Comment by pikzen** [comment]
Sorry, got terribly busy and didn't have time to explore it further!
Absolutely, go ahead and close it

Le mer. 23 août 2023, 12:46 AM, Saket Narayan ***@***.***> a
écrit :
